### ISSUE TITLE
Is this py2, py3, or both?

### ISSUE THREAD

**Issue by tseemann** [nhoffman/alnvu#9]
Unclear from docs.

**Comment by nhoffman** [comment]
Hmm, the readme does say 3.5+ under "dependencies" (as does metadata in setup.py). Feel free to suggest how I can make this any clearer.

**Comment by tseemann** [comment]
Sorry i completely missed it. it does say 2.7 _and_ 3.5+

**Comment by nhoffman** [comment]
No worries - thanks for having a look.
